In [6]:
import numpy as np

In [7]:
#creating a single dimensional numpy array.
#Single dimensional array is created using a single list.

array_numpy = np.array([1,2,3])
array_numpy

array([1, 2, 3])

In [8]:
# multidimensional array 
# Multi-Dimnesional Array is created using multiple tuple inside a list.

multi_array = np.array([(1,2,3),(2,3,4)])
multi_array

array([[1, 2, 3],
       [2, 3, 4]])

In [9]:
#distinguising between list and numpy array
# checking the memory consumption of list and array of the same size

import time
import sys
lst = [x for x in range(1000)]
print(f"Size of single element of list in bytes is {sys.getsizeof(lst[0])}")
print(f"Size of list is {sys.getsizeof(lst)*len(lst)}")
numpy_array  = np.random.rand(1000)
print(f"Size of single element of numpy in bytes is {(numpy_array.itemsize)}")
print(f"Size of numpy is {(numpy_array.itemsize*numpy_array.size)}")

#time comparision
lst2 = [x for x in range(100000)]
numpy_array2 = np.random.rand(100000)
lst3 = [x for x in range(100000)]
numpy_array3 = np.random.rand(100000)


initial_time = time.time()

list_result = [(a*b) for a,b in zip(lst3,lst2)]
print(f"List results time taken is {(time.time() - initial_time)*1000} miliseconds")


time.sleep(3)

new_time  = time.time()
array_result = numpy_array3 * numpy_array2
print(f"Numpy Array results time taken is {(time.time() - new_time)} miliseconds")




#Therefore the list consumes more memory than the numpy and for the larger datasets the operation of list would be comparatively slower
#than the performance of the numpy array

Size of single element of list in bytes is 24
Size of list is 8856000
Size of single element of numpy in bytes is 8
Size of numpy is 8000
List results time taken is 5.291938781738281 miliseconds
Numpy Array results time taken is 0.0006568431854248047 miliseconds


In [10]:
#converting list to numpy arrays

lst = [x for x in range(0,100)]
arr = np.array(lst)


#converting list to array using asarray
lst2 = [1,2,6,4,9,34,77,3,6]
arr2 = np.asarray(lst2)
print(f"List = {lst2}")
print(f"Array = {arr2}")

arr3 = np.asarray(arr2)
arr4 = np.array(arr2)
arr3[2] = 99

print(f"Array1 = {arr2}")
print(f"Array2 = {arr3}")
print(f"Array3 = {arr4}")

#difference between asarray and array is that array will make the copy of the original object and asarray will mirror the original object
#which take changes in the array when the original array is updated

List = [1, 2, 6, 4, 9, 34, 77, 3, 6]
Array = [ 1  2  6  4  9 34 77  3  6]
Array1 = [ 1  2 99  4  9 34 77  3  6]
Array2 = [ 1  2 99  4  9 34 77  3  6]
Array3 = [ 1  2  6  4  9 34 77  3  6]


In [11]:
#accessing the array index

arr = np.array([[1,2,3,4,5],
                [2,5,4,3,5],
                [4,3,2,5,3],
                [1,0,8,6,5]])

#get 2 from the 3rd row

sliced_array = arr[2,2]
print(f"First slicing = {sliced_array}")

#get first 2 elements of 1,2,3,4 rows
sliced_array2 = arr[:,:2]
print(f"Second slicing = {sliced_array2}")

#array with all rows and alternate columns
sliced_array3 = arr[:,::2]
print(f"Third slicing = {sliced_array3}")


First slicing = 2
Second slicing = [[1 2]
 [2 5]
 [4 3]
 [1 0]]
Third slicing = [[1 3 5]
 [2 4 5]
 [4 2 3]
 [1 8 5]]


In [12]:
#creating random array

#generate random integer from 0-100
random_int = np.random.randint(0,100)
print(random_int)

random_float = np.random.rand()
print(random_float)

random_array_int = np.random.randint(55,100,size=(100))
print(random_array_int)

random_array_float = np.random.rand(22)
print(random_array_float)

#create random 2d arrays

# 3 rows, 5 columns
random_2d = np.random.rand(3,5)
print(random_2d)

#generate random number from array
arr = [1,6,4,6,8,4,3,6]

arr_random = np.random.choice(arr)
print(arr_random)

arr_random2 = np.random.choice(arr,size=(2,3))
print(arr_random2)

#checking th dimensions of the array
print("Dimensions of the array")
print(arr_random2.ndim)
print(random_array_float.ndim)

d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(d.ndim)

41
0.0017448032332837426
[94 78 84 68 83 67 75 88 85 81 57 60 77 70 70 73 66 71 64 63 65 67 83 56
 91 87 63 92 61 64 57 73 64 60 90 90 70 90 71 62 85 73 75 98 79 75 61 81
 95 96 56 64 96 56 62 95 92 61 94 89 69 85 90 87 93 81 98 62 72 73 65 86
 57 61 76 67 91 69 87 74 60 58 88 71 85 74 83 61 59 64 59 73 70 92 59 89
 86 70 69 99]
[0.38755374 0.71108159 0.92935369 0.28960394 0.71005893 0.44835985
 0.290646   0.01398243 0.26964582 0.96710768 0.20000233 0.48850483
 0.99732091 0.81330986 0.06232822 0.77095847 0.37147996 0.46303831
 0.72107749 0.74388433 0.26114372 0.94867944]
[[0.38807369 0.97321803 0.24668994 0.45326766 0.4919663 ]
 [0.38246879 0.6338629  0.16613058 0.74032736 0.91825977]
 [0.6006626  0.80578281 0.0158611  0.14522871 0.34044119]]
6
[[8 3 4]
 [4 3 1]]
Dimensions of the array
2
1
3


In [96]:
#data types in numpy array
import numpy as np

arr = np.array(['apple', 'banana', 'cherry'])

print(f"1st Array dtype = {arr.dtype}")

arr2 = np.array([0.234,1,66,0.0092])
print(f"Data type of 2nd array = {arr2.dtype}")

arr3 = np.array([True,False,True,False])
print(f"Data type of 3rd array = {arr3.dtype}")

arr4 = np.array([1,2,3,4,5,6])
print(f"Data type of 4th array = {arr4.dtype}")



1st Array dtype = <U6
Data type of 2nd array = float64
Data type of 3rd array = bool
Data type of 4th array = int64


In [98]:
#copy vs view in numpy

arr1  = np.array([1,2,3,4,5,6,7,8,9])
arr2 = arr1.copy()
arr3 = arr1.view()

arr1[2]=99
print(f"Original Array {arr1}")
print(f"Copied Array {arr2}")
print(f"View Array {arr3}")

#Therefore copy just makes the copy of the array but view mirrors the array and it's operations as well

Original Array [ 1  2 99  4  5  6  7  8  9]
Copied Array [1 2 3 4 5 6 7 8 9]
View Array [ 1  2 99  4  5  6  7  8  9]


In [13]:
#reshape array
arr1 = np.array([1,2,3,4,5,6,7,8,9])
new_arr = arr1.reshape(3,3)
print(new_arr)

arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_arr2 = arr2.reshape(4,3)
new_arr3 = arr2.reshape(3,4)
print(new_arr2)
print(new_arr3)
print(new_arr3.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [190]:
#search in array
arr = np.array([[11,25,65,76,88,9],
                [44,88,88,88,65,65]])
print(np.where(arr == 88))
print(np.where(arr==65))

(array([0, 1, 1, 1]), array([4, 1, 2, 3]))
(array([0, 1, 1]), array([2, 4, 5]))


In [118]:
#sorting in array
arr = np.array([[11,25,65,76,88,9],
                [44,88,88,88,65,65]])
x = np.sort(arr)
print(x)

arr1 = np.array(["Cherry","apple","BANANA","Zebra","AAAAA","aaaaa"])
print(np.sort(arr1))

arr2 = np.random.rand(22)
print(np.sort(arr2))

arr3 = np.random.choice(a=[True,False],size=(4,7))
print(arr3)
print(np.sort(arr3))

[[ 9 11 25 65 76 88]
 [44 65 65 88 88 88]]
['AAAAA' 'BANANA' 'Cherry' 'Zebra' 'aaaaa' 'apple']
[0.04455239 0.0704944  0.12109692 0.25133056 0.26706812 0.27420094
 0.32012698 0.35232696 0.3691892  0.39424254 0.39969782 0.45172447
 0.47798159 0.54361659 0.58306767 0.6472159  0.68901842 0.71596428
 0.84594049 0.88117402 0.96337652 0.98536721]
[[False  True  True  True  True  True False]
 [False False False  True False  True  True]
 [ True False  True  True False  True  True]
 [ True False False  True  True False False]]
[[False False  True  True  True  True  True]
 [False False False False  True  True  True]
 [False False  True  True  True  True  True]
 [False False False False  True  True  True]]


In [14]:
#numpy zeros
arr = np.zeros((2,4),dtype=int)
print(arr)

arr2 = np.zeros((2,4),dtype=float)
print(arr2)

arr3 = np.zeros((2,4),dtype=[('x','float'),('y','int')])
print(arr3)

[[0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[(0., 0) (0., 0) (0., 0) (0., 0)]
 [(0., 0) (0., 0) (0., 0) (0., 0)]]


In [126]:
#numpy ones
arr = np.ones((2,4),dtype=float)
print(arr)
arr1 = np.ones((2,4),dtype=int)
print(arr1)
arr3 = np.ones((2,4),dtype=[('x','float'),('y','int')])
print(arr3)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]]
[[(1., 1) (1., 1) (1., 1) (1., 1)]
 [(1., 1) (1., 1) (1., 1) (1., 1)]]


In [140]:
#numpy fill
arr = np.empty((3,3))


#using for loop
for i in range(len(arr)):
    for j in range(len(arr)):
        arr[i][j]=1

print(arr)
print("\nsecond array\n")
arr1 = np.empty((3,3))
arr1.fill(1)
print(arr1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

second array

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [159]:
#saving files in numpy
data = np.random.rand(100)
print(data)
np.save('data.npy', data)


[0.72298066 0.93988339 0.89411527 0.51031352 0.14473385 0.30368166
 0.7260526  0.04432156 0.33631657 0.55166805 0.9405161  0.80682563
 0.49258444 0.58773357 0.27918842 0.01008206 0.22632039 0.24881314
 0.42017    0.24799395 0.71687433 0.92434377 0.37578859 0.67693661
 0.61678814 0.26696419 0.11963739 0.49507055 0.62908825 0.46989442
 0.52061117 0.92357512 0.77058117 0.39647921 0.77771491 0.99054047
 0.74601372 0.702142   0.01885636 0.90431824 0.87579695 0.25881491
 0.8462786  0.93498357 0.23439522 0.73379737 0.46611947 0.12945275
 0.67810334 0.01615384 0.42164966 0.12042419 0.94039726 0.2216709
 0.55219178 0.78631226 0.76015326 0.60243953 0.10426947 0.06805272
 0.68200606 0.04195613 0.35868199 0.90269818 0.81465366 0.93448298
 0.24573323 0.41686395 0.39436598 0.2968848  0.1498334  0.4911055
 0.43333343 0.03057222 0.94357019 0.79339561 0.96032418 0.97918002
 0.6792027  0.68371958 0.76791439 0.53061593 0.75946275 0.79923703
 0.96758725 0.94737234 0.75030951 0.14651599 0.47601396 0.703957

In [160]:
#loading numpy data
#numpy is able to load the pickle file as well
data = np.load("data.npy")
print(data)

[0.72298066 0.93988339 0.89411527 0.51031352 0.14473385 0.30368166
 0.7260526  0.04432156 0.33631657 0.55166805 0.9405161  0.80682563
 0.49258444 0.58773357 0.27918842 0.01008206 0.22632039 0.24881314
 0.42017    0.24799395 0.71687433 0.92434377 0.37578859 0.67693661
 0.61678814 0.26696419 0.11963739 0.49507055 0.62908825 0.46989442
 0.52061117 0.92357512 0.77058117 0.39647921 0.77771491 0.99054047
 0.74601372 0.702142   0.01885636 0.90431824 0.87579695 0.25881491
 0.8462786  0.93498357 0.23439522 0.73379737 0.46611947 0.12945275
 0.67810334 0.01615384 0.42164966 0.12042419 0.94039726 0.2216709
 0.55219178 0.78631226 0.76015326 0.60243953 0.10426947 0.06805272
 0.68200606 0.04195613 0.35868199 0.90269818 0.81465366 0.93448298
 0.24573323 0.41686395 0.39436598 0.2968848  0.1498334  0.4911055
 0.43333343 0.03057222 0.94357019 0.79339561 0.96032418 0.97918002
 0.6792027  0.68371958 0.76791439 0.53061593 0.75946275 0.79923703
 0.96758725 0.94737234 0.75030951 0.14651599 0.47601396 0.703957

In [59]:
#Stacking in numpy array

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[0,2,4],[1,3,5]])

#Vertical Stacking

c = np.vstack((a,b))
print(f"Vertical Stacking = {c}")

#horizontal stacking

d= np.hstack((a,b))
print(f"Horizontal Stacking = {d}")

#column stackin
f = [1,2]
e = np.column_stack((a,f))
print(f"column Stacking = {e}")

#concatinating array
g = np.concatenate((a,b),axis=0)
h = np.concatenate((a,b),axis=1)

print(f"Row concatenation = {g}")
print(f"Column concatenation = {h}")

Vertical Stacking = [[1 2 3]
 [4 5 6]
 [0 2 4]
 [1 3 5]]
Horizontal Stacking = [[1 2 3 0 2 4]
 [4 5 6 1 3 5]]
column Stacking = [[1 2 3 1]
 [4 5 6 2]]
Row concatenation = [[1 2 3]
 [4 5 6]
 [0 2 4]
 [1 3 5]]
Column concatenation = [[1 2 3 0 2 4]
 [4 5 6 1 3 5]]


In [70]:
#array splitting

a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])
hor_axis = np.hsplit(a,3)
print(f"Horizontal spliting = {hor_axis}")

ver_axis = np.vsplit(a,2)
print(f"Vertical Spliting = {ver_axis}")

Horizontal spliting = [array([[1, 3],
       [2, 4]]), array([[5, 7],
       [6, 8]]), array([[ 9, 11],
       [10, 12]])]
Vertical Spliting = [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]


In [177]:
#creating the numpy array into dataframe
import pandas as pd
a = np.array([["apple","2"],["banana","6"],["cat","8"],["elephant","6"]])
c = pd.DataFrame(a,columns=["Objects","Count"],index=range(1,5))
print(c)



    Objects Count
1     apple     2
2    banana     6
3       cat     8
4  elephant     6


In [179]:
#creating the numpy array into dataframe
import pandas as pd
a = np.array([("Cezane Karki","2021"),("Pratik Thapa","2020"),("Arjan Poudel","2022")])
b= pd.DataFrame(a,columns=["Name","Graduation Year"], index= range(1,4))
print(b)



           Name Graduation Year
1  Cezane Karki            2021
2  Pratik Thapa            2020
3  Arjan Poudel            2022


In [4]:
import numpy as np 
data = np.loadtxt("../Day 6 Pandas/try_data.csv", delimiter =",",dtype=str)
data

ValueError: Wrong number of columns at line 92

In [5]:
import numpy as np 
data = np.genfromtxt("../Day 6 Pandas/try_data.csv", delimiter =",",dtype=str)
data

ValueError: Some errors were detected !
    Line #92 (got 5 columns instead of 4)
    Line #199 (got 5 columns instead of 4)
    Line #585 (got 5 columns instead of 4)
    Line #905 (got 5 columns instead of 4)