In [1]:
import numpy as np

In [2]:
#creating a single dimensional numpy array.
#Single dimensional array is created using a single list.

array_numpy = np.array([1,2,3])
array_numpy

array([1, 2, 3])

In [3]:
# multidimensional array 
# Multi-Dimnesional Array is created using multiple tuple inside a list.

multi_array = np.array([(1,2,3),(2,3,4)])
multi_array

array([[1, 2, 3],
       [2, 3, 4]])

In [28]:
#distinguising between list and numpy array
# checking the memory consumption of list and array of the same size

import time
import sys
lst = [x for x in range(1000)]
print(f"Size of single element of list in bytes is {sys.getsizeof(lst[0])}")
print(f"Size of list is {sys.getsizeof(lst)*len(lst)}")
numpy_array  = np.random.rand(1000)
print(f"Size of single element of numpy in bytes is {(numpy_array.itemsize)}")
print(f"Size of numpy is {(numpy_array.itemsize*numpy_array.size)}")

#time comparision
lst2 = [x for x in range(100000)]
numpy_array2 = np.random.rand(100000)
lst3 = [x for x in range(100000)]
numpy_array3 = np.random.rand(100000)


initial_time = time.time()

list_result = [(a*b) for a,b in zip(lst3,lst2)]
print(f"List results time taken is {(time.time() - initial_time)*1000} miliseconds")


time.sleep(3)

new_time  = time.time()
array_result = numpy_array3 * numpy_array2
print(f"Numpy Array results time taken is {(time.time() - new_time)} miliseconds")




#Therefore the list consumes more memory than the numpy and for the larger datasets the operation of list would be comparatively slower
#than the performance of the numpy array

Size of single element of list in bytes is 24
Size of list is 8856000
Size of single element of numpy in bytes is 8
Size of numpy is 8000
List results time taken is 6.382226943969727 miliseconds
Numpy Array results time taken is 0.0005319118499755859 miliseconds


In [44]:
#converting list to numpy arrays

lst = [x for x in range(0,100)]
arr = np.array(lst)


#converting list to array using asarray
lst2 = [1,2,6,4,9,34,77,3,6]
arr2 = np.asarray(lst2)
print(f"List = {lst2}")
print(f"Array = {arr2}")

arr3 = np.asarray(arr2)
arr4 = np.array(arr2)
arr3[2] = 99

print(f"Array1 = {arr2}")
print(f"Array2 = {arr3}")
print(f"Array3 = {arr4}")

#difference between asarray and array is that array will make the copy of the original object and asarray will mirror the original object
#which take changes in the array when the original array is updated

List = [1, 2, 6, 4, 9, 34, 77, 3, 6]
Array = [ 1  2  6  4  9 34 77  3  6]
Array1 = [ 1  2 99  4  9 34 77  3  6]
Array2 = [ 1  2 99  4  9 34 77  3  6]
Array3 = [ 1  2  6  4  9 34 77  3  6]


In [49]:
#accessing the array index

arr = np.array([[1,2,3,4,5],
                [2,5,4,3,5],
                [4,3,2,5,3],
                [1,0,8,6,5]])

#get 2 from the 3rd row

sliced_array = arr[2,2]
print(f"First slicing = {sliced_array}")

#get first 2 elements of 1,2,3,4 rows
sliced_array2 = arr[:,:2]
print(f"Second slicing = {sliced_array2}")

#array with all rows and alternate columns
sliced_array3 = arr[:,::2]
print(f"Third slicing = {sliced_array3}")


First slicing = 2
Second slicing = [[1 2]
 [2 5]
 [4 3]
 [1 0]]
Third slicing = [[1 3 5]
 [2 4 5]
 [4 2 3]
 [1 8 5]]


In [87]:
#creating random array

#generate random integer from 0-100
random_int = np.random.randint(0,100)
print(random_int)

random_float = np.random.rand()
print(random_float)

random_array_int = np.random.randint(55,100,size=(100))
print(random_array_int)

random_array_float = np.random.rand(22)
print(random_array_float)

#create random 2d arrays

# 3 rows, 5 columns
random_2d = np.random.rand(3,5)
print(random_2d)

#generate random number from array
arr = [1,6,4,6,8,4,3,6]

arr_random = np.random.choice(arr)
print(arr_random)

arr_random2 = np.random.choice(arr,size=(2,3))
print(arr_random2)

75
0.38342042458402437
[56 92 90 98 96 61 68 56 72 57 55 74 80 89 66 99 65 87 66 58 66 79 78 77
 84 98 90 66 57 91 96 82 60 70 57 95 71 97 68 71 56 63 60 63 57 80 69 89
 84 78 72 59 68 68 72 80 77 97 77 92 93 60 55 85 62 78 73 70 66 91 99 79
 76 93 61 65 77 72 58 93 61 71 58 60 95 98 94 67 77 76 91 69 75 81 75 72
 82 95 79 98]
[0.69270361 0.83923508 0.32533894 0.80236103 0.35198254 0.44719027
 0.49599602 0.60638444 0.84408884 0.21491645 0.65755103 0.71493132
 0.24276617 0.31994575 0.54551799 0.36947238 0.18205454 0.21832497
 0.57551077 0.58683462 0.79606448 0.88075046]
[[0.02402811 0.09506687 0.21064757 0.76161742 0.45099383]
 [0.9130475  0.67378293 0.47697514 0.81332678 0.05969237]
 [0.06785407 0.05673761 0.32614971 0.06662649 0.82239343]]
4
[[6 6 1]
 [6 1 8]]


In [59]:
#Stacking in numpy array

a = np.array([[1,2,3],[4,5,6]])
b = np.array([[0,2,4],[1,3,5]])

#Vertical Stacking

c = np.vstack((a,b))
print(f"Vertical Stacking = {c}")

#horizontal stacking

d= np.hstack((a,b))
print(f"Horizontal Stacking = {d}")

#column stackin
f = [1,2]
e = np.column_stack((a,f))
print(f"column Stacking = {e}")

#concatinating array
g = np.concatenate((a,b),axis=0)
h = np.concatenate((a,b),axis=1)

print(f"Row concatenation = {g}")
print(f"Column concatenation = {h}")

Vertical Stacking = [[1 2 3]
 [4 5 6]
 [0 2 4]
 [1 3 5]]
Horizontal Stacking = [[1 2 3 0 2 4]
 [4 5 6 1 3 5]]
column Stacking = [[1 2 3 1]
 [4 5 6 2]]
Row concatenation = [[1 2 3]
 [4 5 6]
 [0 2 4]
 [1 3 5]]
Column concatenation = [[1 2 3 0 2 4]
 [4 5 6 1 3 5]]


In [70]:
#array splitting

a = np.array([[1, 3, 5, 7, 9, 11],
              [2, 4, 6, 8, 10, 12]])
hor_axis = np.hsplit(a,3)
print(f"Horizontal spliting = {hor_axis}")

ver_axis = np.vsplit(a,2)
print(f"Vertical Spliting = {ver_axis}")

Horizontal spliting = [array([[1, 3],
       [2, 4]]), array([[5, 7],
       [6, 8]]), array([[ 9, 11],
       [10, 12]])]
Vertical Spliting = [array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]
